### ISSUE TITLE
[bug]: Backup/Restore certman

### ISSUE THREAD

**Issue by sdwru** [FreePBX/issue-tracker#359]
### FreePBX Version

FreePBX 17

### Issue Description

Backup from FPBX 15, Restoring to FPBX 17 via `fwconsole backup` I encountered the following error.

```
 Restoring from certman [FreePBX\modules\Certman\Restore]
Array to string conversion on line 1461 of file /var/www/html/admin/modules/certman/Certman.class.php
#0 [internal function]: Whoops\Run->handleError()
#1 /var/www/html/admin/modules/certman/Certman.class.php(1461): PDOStatement->execute()
#2 /var/www/html/admin/modules/certman/Restore.php(41): FreePBX\modules\Certman->saveCSR()
#3 /var/www/html/admin/modules/certman/Restore.php(27): FreePBX\modules\Certman\Restore->processConfigs()
#4 /var/www/html/admin/modules/backup/Handlers/Restore/Common.php(139): FreePBX\modules\Certman\Restore->runRestore()
#5 /var/www/html/admin/modules/backup/Handlers/Restore/Common.php(127): FreePBX\modules\Backup\Handlers\Restore\Common->runRestore()
#6 /var/www/html/admin/modules/backup/Handlers/Restore/Multiple.php(70): FreePBX\modules\Backup\Handlers\Restore\Common->processModule()
#7 /var/www/html/admin/modules/backup/Console/Backup.class.php(371): FreePBX\modules\Backup\Handlers\Restore\Multiple->process()
#8 /var/www/html/admin/libraries/Composer/vendor/symfony/console/Command/Command.php(312): FreePBX\Console\Command\Backup->execute()
#9 /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php(1022): Symfony\Component\Console\Command\Command->run()
#10 /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand()
#11 /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun()
#12 /var/lib/asterisk/bin/fwconsole(163): Symfony\Component\Console\Application->run()
```

### Operating Environment

Latest FPBX 17

**Comment by kapilgupta01** [comment]
certman v17.0.3.13
