### ISSUE TITLE
[bug]: ucp service failing to run

### ISSUE THREAD

**Issue by billsimon** [FreePBX/issue-tracker#42]
### FreePBX Version

FreePBX 17

### Issue Description

Installed FreePBX 17 using the Debian 12 install script.

The ucp service continually restarts. Output from `fwconsole pm2 --log ucp` : 

```
2024-03-16 15:15 +00:00: Starting FreePBX...
OUT > 2024-03-16 15:15 +00:00: 28800000
OUT > 2024-03-16 15:15 +00:00: 14400000
OUT > 2024-03-16 15:15 +00:00: Result set finished
OUT > 2024-03-16 15:15 +00:00: FreePBX is Ready!
OUT > 2024-03-16 15:15 +00:00: Asterisk version is: 21.0.2
OUT > 
==> /var/log/asterisk/ucp_err.log <==
2024-03-16 15:15 +00:00: Error: Cannot find module '/var/www/html/admin/modules/ucp/node/node_modules/debug/src/index.js'. Please verify that the package.json has a valid "main" entry
2024-03-16 15:15 +00:00:     at tryPackage (node:internal/modules/cjs/loader:437:19)
2024-03-16 15:15 +00:00:     at Module._findPath (node:internal/modules/cjs/loader:705:18)
2024-03-16 15:15 +00:00:     at Module._resolveFilename (node:internal/modules/cjs/loader:1120:27)
2024-03-16 15:15 +00:00:     at Hook._require.Module.require (/var/www/html/admin/modules/pm2/node/node_modules/require-in-the-middle/index.js:81:25)
2024-03-16 15:15 +00:00:     at require (node:internal/modules/helpers:177:18)
2024-03-16 15:15 +00:00:     at Object.<anonymous> (/var/www/html/admin/modules/ucp/node/node_modules/finalhandler/index.js:14:13)
2024-03-16 15:15 +00:00:     at Module._compile (node:internal/modules/cjs/loader:1356:14)
2024-03-16 15:15 +00:00:     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
2024-03-16 15:15 +00:00:     at Module.load (node:internal/modules/cjs/loader:1197:32)
2024-03-16 15:15 +00:00:     at Module._load (node:internal/modules/cjs/loader:1013:12) {
2024-03-16 15:15 +00:00:   code: 'MODULE_NOT_FOUND',
2024-03-16 15:15 +00:00:   path: '/var/www/html/admin/modules/ucp/node/node_modules/debug/package.json',
2024-03-16 15:15 +00:00:   requestPath: 'debug'
2024-03-16 15:15 +00:00: }
```

### Operating Environment

Debian 12
FreePBX 17
ucp 17.0.4.12

**Comment by ArunbalanNV** [comment]
Thank you for reporting this issue. 
We attempted to reproduce it using the same module version mentioned in this ticket. However, we were unable to replicate the issue on our end.

Based on our analysis, it seems that the node dependency modules may not have been installed properly on your system. 
As a potential workaround, we recommend trying to uninstall and then reinstall the UCP module from the command line using the following commands:
```
fwconsole ma uninstall ucp
fwconsole ma install ucp
```
By doing so, you may uncover any errors or issues that could be preventing the proper installation of the node packages.

Please let us know if you encounter any errors during this process or if the issue persists after reinstalling the module. 

We're here to assist you further in resolving this matter.

**Comment by billsimon** [comment]
Here is an SSH transcript of me uninstalling and reinstalling ucp and the results - the process is still failing to run.

```
root@us-iad01-s2n-1c1g-1:~# fwconsole ma uninstall ucp
The following error(s) occured:
 - Cannot disable: The following modules depend on this one: sms,webrtc
root@us-iad01-s2n-1c1g-1:~# fwconsole ma uninstall ucp --force
Remove all UCP tables
Stopping old running processes...Done
Dropping table ucp_sessions...Done
Module ucp successfully uninstalled
Updating Hooks...Done
root@us-iad01-s2n-1c1g-1:~# fwconsole ma install ucp
Updating tables ucp_sessions...Done
System : debian
Installing/Updating Required Libraries. This may take a while...The following messages are ONLY FOR DEBUGGING. Ignore anything that says 'WARN' or is just a warning
Found npm-cache v0.7.0
Running installation..
[npm-cache] [INFO] using /home/asterisk/.package_cache as cache directory
[npm-cache] [INFO] [composer] Dependency config file /var/www/html/admin/modules/ucp/node/composer.json does not exist. Skipping install
[npm-cache] [INFO] [npm] config file exists
[npm-cache] [INFO] [npm] cli exists
[npm-cache] [INFO] [npm] hash of /var/www/html/admin/modules/ucp/node/package.json: f05cb602e1e1d71218102eca2200f753
[npm-cache] [INFO] [npm] cache exists
[npm-cache] [INFO] [npm] clearing installed dependencies at /var/www/html/admin/modules/ucp/node/node_modules
[npm-cache] [INFO] [npm] ...cleared
[npm-cache] [INFO] [npm] retrieving dependencies from /home/asterisk/.package_cache/npm/9.2.0/f05cb602e1e1d71218102eca2200f753.tar.gz
[npm-cache] [INFO] [bower] Dependency config file /var/www/html/admin/modules/ucp/node/bower.json does not exist. Skipping install
[npm-cache] [INFO] [npm] done extracting
[npm-cache] [INFO] successfully installed all dependencies

Finished updating libraries!
Stopping old running processes...Done
Starting new UCP Node Process...Started with PID 1751988!
Refreshing all UCP Assets, this could take a while...
Generating Module Scripts...Done
Generating Module CSS...Done
Generating Main Scripts...Done
Generating Main CSS...Done
Done!
Generating CSS...Done
Module ucp version 17.0.4.13 successfully installed
Updating Hooks...Done
Chowning directories...Done
root@us-iad01-s2n-1c1g-1:~# fwconsole r
Reload Started
Reload Complete
root@us-iad01-s2n-1c1g-1:~# fwconsole pm2 --list
+---------------------------+---------+--------+----------+--------------------+------+---------+
| Process Name              | PID     | Status | Restarts | Uptime             | CPU  | Mem     |
+---------------------------+---------+--------+----------+--------------------+------+---------+
| core-fastagi              | 195619  | online | 0        | 9 days, 5 hours    | 0%   | 5.89MB  |
| core-calltransfer-monitor | 1737313 | online | 0        | 1 hour, 17 minutes | 0%   | 2.31MB  |
| sangomartapi              | 1738127 | online | 0        | 1 hour, 15 minutes | 0.4% | 38.50MB |
| ucp                       | 1753083 | online | 32       | 54 seconds         | 0%   | 42.09MB |
| restapps                  | 1752693 | online | 0        | 13 seconds         | 0%   | 52.18MB |
+---------------------------+---------+--------+----------+--------------------+------+---------+
root@us-iad01-s2n-1c1g-1:~# fwconsole pm2 --list
+---------------------------+---------+--------+----------+--------------------+------+---------+
| Process Name              | PID     | Status | Restarts | Uptime             | CPU  | Mem     |
+---------------------------+---------+--------+----------+--------------------+------+---------+
| core-fastagi              | 195619  | online | 0        | 9 days, 5 hours    | 0.1% | 6.73MB  |
| core-calltransfer-monitor | 1737313 | online | 0        | 1 hour, 17 minutes | 0%   | 2.31MB  |
| sangomartapi              | 1738127 | online | 0        | 1 hour, 16 minutes | 0.3% | 35.19MB |
| ucp                       | 1753197 | online | 36       | 1 minute           | 0%   | 42.42MB |
| restapps                  | 1752693 | online | 0        | 19 seconds         | 0%   | 52.09MB |
+---------------------------+---------+--------+----------+--------------------+------+---------+
root@us-iad01-s2n-1c1g-1:~# fwconsole pm2 --log ucp
OUT > ==> /var/log/asterisk/ucp_err.log <==
2024-03-25 20:33 +00:00:     at require (node:internal/modules/helpers:177:18)
2024-03-25 20:33 +00:00:     at Object.<anonymous> (/var/www/html/admin/modules/ucp/node/node_modules/finalhandler/index.js:14:13)
2024-03-25 20:33 +00:00:     at Module._compile (node:internal/modules/cjs/loader:1356:14)
2024-03-25 20:33 +00:00:     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
2024-03-25 20:33 +00:00:     at Module.load (node:internal/modules/cjs/loader:1197:32)
2024-03-25 20:33 +00:00:     at Module._load (node:internal/modules/cjs/loader:1013:12) {
2024-03-25 20:33 +00:00:   code: 'MODULE_NOT_FOUND',
2024-03-25 20:33 +00:00:   path: '/var/www/html/admin/modules/ucp/node/node_modules/debug/package.json',
2024-03-25 20:33 +00:00:   requestPath: 'debug'
2024-03-25 20:33 +00:00: }

==> /var/log/asterisk/ucp_out.log <==
2024-03-25 20:33 +00:00: Result set finished
2024-03-25 20:33 +00:00: FreePBX is Ready!
2024-03-25 20:33 +00:00: Asterisk version is: 21.0.2
2024-03-25 20:33 +00:00: Starting FreePBX...
2024-03-25 20:33 +00:00: 28800000
2024-03-25 20:33 +00:00: 14400000
2024-03-25 20:33 +00:00: Result set finished
2024-03-25 20:33 +00:00: FreePBX is Ready!
2024-03-25 20:33 +00:00: Asterisk version is: 21.0.2
2024-03-25 20:33 +00:00: Starting FreePBX...
OUT > 2024-03-25 20:33 +00:00: 28800000
OUT > 2024-03-25 20:33 +00:00: 14400000
OUT > 2024-03-25 20:33 +00:00: Result set finished
OUT > 2024-03-25 20:33 +00:00: FreePBX is Ready!
OUT > 2024-03-25 20:33 +00:00: Asterisk version is: 21.0.2
OUT > 
==> /var/log/asterisk/ucp_err.log <==
2024-03-25 20:33 +00:00: Error: Cannot find module '/var/www/html/admin/modules/ucp/node/node_modules/debug/src/index.js'. Please verify that the package.json has a valid "main" entry
2024-03-25 20:33 +00:00:     at tryPackage (node:internal/modules/cjs/loader:437:19)
2024-03-25 20:33 +00:00:     at Module._findPath (node:internal/modules/cjs/loader:705:18)
2024-03-25 20:33 +00:00:     at Module._resolveFilename (node:internal/modules/cjs/loader:1120:27)
2024-03-25 20:33 +00:00:     at Hook._require.Module.require (/var/www/html/admin/modules/pm2/node/node_modules/require-in-the-middle/index.js:81:25)
2024-03-25 20:33 +00:00:     at require (node:internal/modules/helpers:177:18)
2024-03-25 20:33 +00:00:     at Object.<anonymous> (/var/www/html/admin/modules/ucp/node/node_modules/finalhandler/index.js:14:13)
2024-03-25 20:33 +00:00:     at Module._compile (node:internal/modules/cjs/loader:1356:14)
2024-03-25 20:33 +00:00:     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
2024-03-25 20:33 +00:00:     at Module.load (node:internal/modules/cjs/loader:1197:32)
2024-03-25 20:33 +00:00:     at Module._load (node:internal/modules/cjs/loader:1013:12) {
2024-03-25 20:33 +00:00:   code: 'MODULE_NOT_FOUND',
2024-03-25 20:33 +00:00:   path: '/var/www/html/admin/modules/ucp/node/node_modules/debug/package.json',
2024-03-25 20:33 +00:00:   requestPath: 'debug'
2024-03-25 20:33 +00:00: }
OUT > 
==> /var/log/asterisk/ucp_out.log <==
2024-03-25 20:33 +00:00: Starting FreePBX...
OUT > 2024-03-25 20:33 +00:00: 28800000
OUT > 2024-03-25 20:33 +00:00: 14400000
OUT > 2024-03-25 20:33 +00:00: Result set finished
OUT > 2024-03-25 20:33 +00:00: FreePBX is Ready!
OUT > 2024-03-25 20:33 +00:00: Asterisk version is: 21.0.2
OUT > 
==> /var/log/asterisk/ucp_err.log <==
2024-03-25 20:33 +00:00: Error: Cannot find module '/var/www/html/admin/modules/ucp/node/node_modules/debug/src/index.js'. Please verify that the package.json has a valid "main" entry
2024-03-25 20:33 +00:00:     at tryPackage (node:internal/modules/cjs/loader:437:19)
2024-03-25 20:33 +00:00:     at Module._findPath (node:internal/modules/cjs/loader:705:18)
2024-03-25 20:33 +00:00:     at Module._resolveFilename (node:internal/modules/cjs/loader:1120:27)
2024-03-25 20:33 +00:00:     at Hook._require.Module.require (/var/www/html/admin/modules/pm2/node/node_modules/require-in-the-middle/index.js:81:25)
2024-03-25 20:33 +00:00:     at require (node:internal/modules/helpers:177:18)
2024-03-25 20:33 +00:00:     at Object.<anonymous> (/var/www/html/admin/modules/ucp/node/node_modules/finalhandler/index.js:14:13)
2024-03-25 20:33 +00:00:     at Module._compile (node:internal/modules/cjs/loader:1356:14)
2024-03-25 20:33 +00:00:     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
2024-03-25 20:33 +00:00:     at Module.load (node:internal/modules/cjs/loader:1197:32)
2024-03-25 20:33 +00:00:     at Module._load (node:internal/modules/cjs/loader:1013:12) {
2024-03-25 20:33 +00:00:   code: 'MODULE_NOT_FOUND',
2024-03-25 20:33 +00:00:   path: '/var/www/html/admin/modules/ucp/node/node_modules/debug/package.json',
2024-03-25 20:33 +00:00:   requestPath: 'debug'
2024-03-25 20:33 +00:00: }
OUT > 
==> /var/log/asterisk/ucp_out.log <==
2024-03-25 20:33 +00:00: Starting FreePBX...
OUT > 2024-03-25 20:33 +00:00: 28800000
OUT > 2024-03-25 20:33 +00:00: 14400000
OUT > 2024-03-25 20:33 +00:00: Result set finished
OUT > 2024-03-25 20:33 +00:00: FreePBX is Ready!
OUT > 2024-03-25 20:33 +00:00: Asterisk version is: 21.0.2
OUT > 
==> /var/log/asterisk/ucp_err.log <==
2024-03-25 20:33 +00:00: Error: Cannot find module '/var/www/html/admin/modules/ucp/node/node_modules/debug/src/index.js'. Please verify that the package.json has a valid "main" entry
2024-03-25 20:33 +00:00:     at tryPackage (node:internal/modules/cjs/loader:437:19)
2024-03-25 20:33 +00:00:     at Module._findPath (node:internal/modules/cjs/loader:705:18)
2024-03-25 20:33 +00:00:     at Module._resolveFilename (node:internal/modules/cjs/loader:1120:27)
2024-03-25 20:33 +00:00:     at Hook._require.Module.require (/var/www/html/admin/modules/pm2/node/node_modules/require-in-the-middle/index.js:81:25)
2024-03-25 20:33 +00:00:     at require (node:internal/modules/helpers:177:18)
2024-03-25 20:33 +00:00:     at Object.<anonymous> (/var/www/html/admin/modules/ucp/node/node_modules/finalhandler/index.js:14:13)
2024-03-25 20:33 +00:00:     at Module._compile (node:internal/modules/cjs/loader:1356:14)
2024-03-25 20:33 +00:00:     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
2024-03-25 20:33 +00:00:     at Module.load (node:internal/modules/cjs/loader:1197:32)
2024-03-25 20:33 +00:00:     at Module._load (node:internal/modules/cjs/loader:1013:12) {
2024-03-25 20:33 +00:00:   code: 'MODULE_NOT_FOUND',
2024-03-25 20:33 +00:00:   path: '/var/www/html/admin/modules/ucp/node/node_modules/debug/package.json',
2024-03-25 20:33 +00:00:   requestPath: 'debug'
2024-03-25 20:33 +00:00: }
OUT > 
==> /var/log/asterisk/ucp_out.log <==
2024-03-25 20:33 +00:00: Starting FreePBX...
OUT > 2024-03-25 20:33 +00:00: 28800000
OUT > 2024-03-25 20:33 +00:00: 14400000
OUT > 2024-03-25 20:33 +00:00: Result set finished
OUT > 2024-03-25 20:33 +00:00: FreePBX is Ready!
OUT > 2024-03-25 20:33 +00:00: Asterisk version is: 21.0.2
OUT > 
==> /var/log/asterisk/ucp_err.log <==
2024-03-25 20:33 +00:00: Error: Cannot find module '/var/www/html/admin/modules/ucp/node/node_modules/debug/src/index.js'. Please verify that the package.json has a valid "main" entry
2024-03-25 20:33 +00:00:     at tryPackage (node:internal/modules/cjs/loader:437:19)
2024-03-25 20:33 +00:00:     at Module._findPath (node:internal/modules/cjs/loader:705:18)
2024-03-25 20:33 +00:00:     at Module._resolveFilename (node:internal/modules/cjs/loader:1120:27)
2024-03-25 20:33 +00:00:     at Hook._require.Module.require (/var/www/html/admin/modules/pm2/node/node_modules/require-in-the-middle/index.js:81:25)
2024-03-25 20:33 +00:00:     at require (node:internal/modules/helpers:177:18)
2024-03-25 20:33 +00:00:     at Object.<anonymous> (/var/www/html/admin/modules/ucp/node/node_modules/finalhandler/index.js:14:13)
2024-03-25 20:33 +00:00:     at Module._compile (node:internal/modules/cjs/loader:1356:14)
2024-03-25 20:33 +00:00:     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
2024-03-25 20:33 +00:00:     at Module.load (node:internal/modules/cjs/loader:1197:32)
2024-03-25 20:33 +00:00:     at Module._load (node:internal/modules/cjs/loader:1013:12) {
2024-03-25 20:33 +00:00:   code: 'MODULE_NOT_FOUND',
2024-03-25 20:33 +00:00:   path: '/var/www/html/admin/modules/ucp/node/node_modules/debug/package.json',
2024-03-25 20:33 +00:00:   requestPath: 'debug'
2024-03-25 20:33 +00:00: }
OUT > 
==> /var/log/asterisk/ucp_out.log <==
2024-03-25 20:33 +00:00: Starting FreePBX...
^C
```

**Comment by ArunbalanNV** [comment]
HI @billsimon ,
Thank you for providing the information. 
As a final attempt, please remove the cache file /home/asterisk/.package_cache/npm/9.2.0/f05cb602e1e1d71218102eca2200f753.tar.gz and reinstall the UCP module. 
If this also doesn't work, we will begin a deeper investigation.

**Comment by billsimon** [comment]
Removed cache and ran `fwconsole ma install ucp` to reinstall.

Now ucp node service fails with a different dependency error:

```
2024-03-29 15:03 +00:00: Error: Cannot find module 'mariadb'
2024-03-29 15:03 +00:00: Require stack:
2024-03-29 15:03 +00:00: - /var/www/html/admin/modules/ucp/node/lib/freepbx.js
2024-03-29 15:03 +00:00: - /var/www/html/admin/modules/ucp/node/index.js
2024-03-29 15:03 +00:00:     at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
2024-03-29 15:03 +00:00:     at Hook._require.Module.require (/var/www/html/admin/modules/pm2/node/node_modules/require-in-the-middle/index.js:81:25)
2024-03-29 15:03 +00:00:     at require (node:internal/modules/helpers:177:18)
2024-03-29 15:03 +00:00:     at Object.<anonymous> (/var/www/html/admin/modules/ucp/node/lib/freepbx.js:9:15)
2024-03-29 15:03 +00:00:     at Module._compile (node:internal/modules/cjs/loader:1356:14)
2024-03-29 15:03 +00:00:     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
2024-03-29 15:03 +00:00:     at Module.load (node:internal/modules/cjs/loader:1197:32)
2024-03-29 15:03 +00:00:     at Module._load (node:internal/modules/cjs/loader:1013:12)
2024-03-29 15:03 +00:00:     at Module.require (node:internal/modules/cjs/loader:1225:19)
2024-03-29 15:03 +00:00:     at Hook._require.Module.require (/var/www/html/admin/modules/pm2/node/node_modules/require-in-the-middle/index.js:101:39) {
2024-03-29 15:03 +00:00:   code: 'MODULE_NOT_FOUND',
2024-03-29 15:03 +00:00:   requireStack: [
2024-03-29 15:03 +00:00:     '/var/www/html/admin/modules/ucp/node/lib/freepbx.js',
2024-03-29 15:03 +00:00:     '/var/www/html/admin/modules/ucp/node/index.js'
2024-03-29 15:03 +00:00:   ]
2024-03-29 15:03 +00:00: }

```

**Comment by ArunbalanNV** [comment]
Hi @billsimon,

We are really sorry to hear that you're still experiencing issues. We have been unable to reproduce the problem locally on our end. However, the issue you encountered in your last interaction can potentially be resolved by manually installing the npm package.

Let's try to install that missing package manually from the module directory and restart ucp node process. Please try the following commands:

```
cd /var/www/html/admin/modules/ucp/node
npm install mariadb
fwconsole pm2 --restart ucp
```

Once you've tried this, kindly inform us of the results. We're here to assist you further.

**Comment by billsimon** [comment]
I had to rebuild my lab server after hacking at it too much. On a fresh build, the ucp daemon builds and runs without any problem. Closing ticket.
